[package]
name = "my-plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = [
    "assert_process_allocs",
] }

[lib]
crate-type = ["cdylib"]

[workspace]
members = ["xtask"]
